"""
Django settings for Johnnette project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nu+l98r*50h9m17szqq0yw*x%nc&kv9eoh&eu28^b%hw#jfnd_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False

# ALLOWED_HOSTS = ['*']
ALLOWED_HOSTS = []
# ALLOWED_HOSTS = ['192.168.33.168', 'localhost']
# ALLOWED_HOSTS =['192.168.33.106', 'localhost', '192.168.1.1', '0.0.0.0']  
# ALLOWED_HOSTS =['192.168.1.6', 'localhost', '192.168.1.1', '0.0.0.0']  


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Official_Profile',
    "Shop",
    'Blogs',
    'Error',
    'ckeditor',
    'ckeditor_uploader',
    'bootstrap4',
    'crispy_forms',
]


CKEDITOR_UPLOAD_PATH = "uploads/"


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Johnnette.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'Error Templates')] + [os.path.join(BASE_DIR, 'Official_Profile', 'Johnnette Templates Files')] + [os.path.join(BASE_DIR, 'Shop', 'Shop Templates')] + [os.path.join(BASE_DIR, 'Blogs', 'Blog Templates')] + [os.path.join(BASE_DIR, 'Error', 'Error Templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Johnnette.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'NAME': os.path.join(BASE_DIR , 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE =  'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'Official_Profile', "Johnnette Static Files/")] + [os.path.join(BASE_DIR, 'Shop', 'Shop Static Files/')] + [os.path.join(BASE_DIR, 'Blogs', 'Blog Static Files/')] + [os.path.join(BASE_DIR, 'Error', 'Error Static Files/')]
STATIC_ROOT = os.path.join(PROJECT_DIR, 'static')


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CRISPY_TEMPLATE_PACK = 'bootstrap4'


from django.contrib.messages import constants as message_constant
MESSAGE_TAGS={
    # message_constant.DEBUG: "debug",
    message_constant.ERROR: "danger",
    message_constant.INFO: "info",
    message_constant.SUCCESS: "success",
    message_constant.DEBUG: "warning",
}


#========= Razorpay Credentials ===========
KEY = 'rzp_test_qg6vjrkp4rXSOI'
SECRET = 'aqNzbyAYe3V5Ceiga0ly2sy4'


#=================== To Send Email ====================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = '587'
EMAIL_HOST_USER = 'yk@johnnette.com'  
EMAIL_HOST_PASSWORD = 'hdxiztqbedqajgvt'  
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER