# Generated by Django 4.1.7 on 2023-03-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="prod_id",
            field=models.CharField(default=None, max_length=200),
        ),
    ]
