# Generated by Django 4.1.7 on 2023-03-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Shop", "0002_cart_prod_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="prod_id",
            field=models.CharField(
                blank=True, default=None, max_length=200, null=True, unique=True
            ),
        ),
    ]
