# Generated by Django 4.1.7 on 2023-03-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Shop", "0003_alter_cart_prod_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="order_id",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
