# Generated by Django 4.1.7 on 2023-03-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Shop", "0004_alter_cart_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderplaced",
            name="prod_id",
            field=models.CharField(
                blank=True, default=None, max_length=200, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="orderplaced",
            name="order_id",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
