# Generated by Django 4.1.7 on 2023-03-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Shop", "0005_orderplaced_prod_id_alter_orderplaced_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="email",
            field=models.EmailField(default=None, max_length=256),
        ),
    ]
