# Generated by Django 4.1.7 on 2023-03-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Shop", "0006_address_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="pincode",
            field=models.IntegerField(max_length=6),
        ),
    ]
