# Generated by Django 4.1.7 on 2023-03-23 05:40

import Shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Shop", "0007_alter_address_pincode"),
    ]

    operations = [
        migrations.RemoveField(model_name="address", name="address1",),
        migrations.RemoveField(model_name="address", name="address2",),
        migrations.AddField(
            model_name="address",
            name="area",
            field=models.CharField(
                default=None, max_length=250, verbose_name="Road name, Area, Colony"
            ),
        ),
        migrations.AddField(
            model_name="address", name="home", field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="address",
            name="house_no",
            field=models.CharField(
                default=None, max_length=250, verbose_name="House No. / Building Name"
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="office",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="address",
            name="pincode",
            field=models.IntegerField(
                max_length=6, validators=[Shop.models.validate_pincode]
            ),
        ),
    ]
