# Generated by Django 4.1.7 on 2023-03-17 06:59

import Official_Profile.models
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BoardOfDirectors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "director_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "director_designation",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "director_profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="Johnnette/About/Directors"
                    ),
                ),
                (
                    "linkedin_profile_link",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "verbose_name": "Board Of Directors",
                "verbose_name_plural": "Board Of Directors",
            },
        ),
        migrations.CreateModel(
            name="JobPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_profile_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "job_profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="Johnnette/Job Post"
                    ),
                ),
                (
                    "job_brief",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, max_length=10000, null=True
                    ),
                ),
                (
                    "job_description",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, max_length=10000, null=True
                    ),
                ),
                (
                    "responsibilities",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, max_length=10000, null=True
                    ),
                ),
                (
                    "desired_skill",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, max_length=500, null=True
                    ),
                ),
                (
                    "qualification",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("experience", models.CharField(blank=True, max_length=500, null=True)),
                ("location", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "number_of_openings",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "first_email_address_to_which_resume_will_be_sent",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "second_email_address_to_which_resume_will_be_sent",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={"verbose_name": "Job Post", "verbose_name_plural": "Job Posts",},
        ),
        migrations.CreateModel(
            name="NewsandMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "news_channel_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="Johnnette/News/Thumbnail"
                    ),
                ),
                ("news_title", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "news_content",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "news_channel_link",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "news_thumbnail_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="Johnnette/News/Logo"
                    ),
                ),
                (
                    "news_video_id",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "verbose_name": "News And Media",
                "verbose_name_plural": "News And Media",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "product_description",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
            ],
            options={"verbose_name": "Product", "verbose_name_plural": "Products",},
        ),
        migrations.CreateModel(
            name="SeniorManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "employee_designation",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "employee_profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Johnnette/About/Senior Management",
                    ),
                ),
                (
                    "linkedin_profile_link",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "verbose_name": "Senior Management",
                "verbose_name_plural": "Senior Management",
            },
        ),
        migrations.CreateModel(
            name="ProductSpecsOnSlides",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wingspan", models.CharField(blank=True, max_length=500, null=True)),
                ("length", models.CharField(blank=True, max_length=500, null=True)),
                ("height", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "aircraft_weight",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("payloads", models.CharField(blank=True, max_length=500, null=True)),
                ("propulsion", models.CharField(blank=True, max_length=500, null=True)),
                ("material", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "cruise_speed",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "max_flight_altitude",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "max_launch_altitude",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("endurance", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "maximum_speed",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "data_link_range",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "operating_temprature",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "launch_recovery",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "communication",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "operational_range",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "max_flight_distance",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "operational_radius",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "max_live_video_operational_radius",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("navigation", models.CharField(blank=True, max_length=500, null=True)),
                ("msl", models.CharField(blank=True, max_length=500, null=True)),
                ("feature1", models.CharField(blank=True, max_length=500, null=True)),
                ("feature2", models.CharField(blank=True, max_length=500, null=True)),
                ("feature3", models.CharField(blank=True, max_length=500, null=True)),
                ("feature4", models.CharField(blank=True, max_length=500, null=True)),
                ("feature5", models.CharField(blank=True, max_length=500, null=True)),
                ("feature6", models.CharField(blank=True, max_length=500, null=True)),
                ("advantage1", models.CharField(blank=True, max_length=500, null=True)),
                ("advantage2", models.CharField(blank=True, max_length=500, null=True)),
                ("advantage3", models.CharField(blank=True, max_length=500, null=True)),
                ("advantage4", models.CharField(blank=True, max_length=500, null=True)),
                ("advantage5", models.CharField(blank=True, max_length=500, null=True)),
                ("advantage6", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ProductSlideSpecs",
                        to="Official_Profile.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Specs On Slides",
                "verbose_name_plural": "Product Specs On Slides",
            },
        ),
        migrations.CreateModel(
            name="ProductSpecsOnBannerAndDetailedDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operational_range",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "flight_time",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "aircraft_weight",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "product_detailed_description",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, max_length=2000, null=True
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="BannerSpecs",
                        to="Official_Profile.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Specs On Banner",
                "verbose_name_plural": "Product Specs On Banner",
            },
        ),
        migrations.CreateModel(
            name="ProductPageImagesAndVideos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_banner_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=Official_Profile.models.ProductPageImagesAndVideos.banner,
                    ),
                ),
                (
                    "product_banner_video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=Official_Profile.models.ProductPageImagesAndVideos.bannerVideo,
                    ),
                ),
                (
                    "product_wireframe_image_for_desktop",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=Official_Profile.models.ProductPageImagesAndVideos.descriptionImagesDesktop,
                    ),
                ),
                (
                    "product_wireframe_image_for_mobile",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=Official_Profile.models.ProductPageImagesAndVideos.descriptionImagesMobile,
                    ),
                ),
                (
                    "product_slider_desktop_image1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=Official_Profile.models.ProductPageImagesAndVideos.productDesktopSliderImages,
                    ),
                ),
                (
                    "product_slider_desktop_image2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=Official_Profile.models.ProductPageImagesAndVideos.productDesktopSliderImages,
                    ),
                ),
                (
                    "product_slider_desktop_image3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=Official_Profile.models.ProductPageImagesAndVideos.productDesktopSliderImages,
                    ),
                ),
                (
                    "product_slider_desktop_image4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=Official_Profile.models.ProductPageImagesAndVideos.productDesktopSliderImages,
                    ),
                ),
                (
                    "product_slider_mobile_image1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=Official_Profile.models.ProductPageImagesAndVideos.productMobileSliderImages,
                    ),
                ),
                (
                    "product_slider_mobile_image2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=Official_Profile.models.ProductPageImagesAndVideos.productMobileSliderImages,
                    ),
                ),
                (
                    "product_slider_mobile_image3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=Official_Profile.models.ProductPageImagesAndVideos.productMobileSliderImages,
                    ),
                ),
                (
                    "product_slider_mobile_image4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=Official_Profile.models.ProductPageImagesAndVideos.productMobileSliderImages,
                    ),
                ),
                (
                    "product_animation_wireframe_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=Official_Profile.models.ProductPageImagesAndVideos.productAnimationImages,
                    ),
                ),
                (
                    "product_animation_rander_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=Official_Profile.models.ProductPageImagesAndVideos.productAnimationImages,
                    ),
                ),
                (
                    "product_video_thumbnail_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=Official_Profile.models.ProductPageImagesAndVideos.productVideoThumbnail,
                    ),
                ),
                (
                    "product_Intro_video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=Official_Profile.models.ProductPageImagesAndVideos.productVideoThumbnail,
                    ),
                ),
                (
                    "product_field_image1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=Official_Profile.models.ProductPageImagesAndVideos.productFieldImages,
                    ),
                ),
                (
                    "product_field_image2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=Official_Profile.models.ProductPageImagesAndVideos.productFieldImages,
                    ),
                ),
                (
                    "product_field_image3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=Official_Profile.models.ProductPageImagesAndVideos.productFieldImages,
                    ),
                ),
                (
                    "product_field_image4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=Official_Profile.models.ProductPageImagesAndVideos.productFieldImages,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ImagesAndVideos",
                        to="Official_Profile.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Images and Videos",
                "verbose_name_plural": "Product Images and Videos",
            },
        ),
        migrations.CreateModel(
            name="HomePageProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_home_page_desktop_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=Official_Profile.models.HomePageProduct.desktop,
                    ),
                ),
                (
                    "product_home_page_mobile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=Official_Profile.models.HomePageProduct.mobile,
                    ),
                ),
                (
                    "product_description",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "product",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Official_Profile.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product On Home Page",
                "verbose_name_plural": "Products On Home Page",
            },
        ),
    ]
